name: vista_flicks
description: "Vista Reels"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.0.1+15

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  icons_plus: ^5.0.0
  toastification: ^3.0.1
  shared_preferences: ^2.3.4
  image: ^4.5.2
  custom_refresh_indicator: ^4.0.1
  readmore: ^3.0.0
  share_plus: ^10.1.3
  flutter_otp_text_field: ^1.4.0+2
  otp_text_field: ^1.1.3
  gif: ^2.3.0
  country_picker: ^2.0.27
  # flutter_facebook_auth: ^7.1.1
  persistent_bottom_nav_bar_v2: ^5.3.1
  qr_code_scanner_plus: ^2.0.9+1
  direct_select: ^2.0.0
  # chewie: ^1.10.0
  video_player: ^2.9.2
  youtube_explode_dart: ^2.3.10
  flutter_swiper_view: ^1.1.8
  flutter_rating_bar: ^4.0.1
#  android_intent_plus: ^5.3.0
  google_fonts: ^6.2.1

  #Local Database
  hive: 2.2.3
  hive_flutter: 1.1.0

  #State Management
  flutter_riverpod: ^2.6.1

  #Storage and permission
  path_provider: 2.1.5
  #  android_path_provider: 0.3.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  #  wechat_assets_picker: 8.6.3
  flutter_svg: ^2.0.17
  file_picker: ^9.0.2
  permission_handler: ^11.4.0
  lottie: 3.2.0
  flutter_image_compress: ^2.4.0

  #Localization and screen
  easy_localization: ^3.0.7+1
  flutter_screenutil: ^5.9.3
  responsive_builder: ^0.7.1
  country_code_picker: ^3.2.0

  #Network
  dio: ^5.8.0+1
  flutter_offline: ^4.0.0
  webview_flutter: ^4.10.0

  #Loaders
  shimmer: 3.0.0
  loading_animation_widget: ^1.3.0

  #Other Widgets
  pin_code_fields: 8.0.1
  dropdown_button2: 2.3.9
  flutter_slidable: ^3.1.2
  dotted_line: 3.2.3

  #Device Info
  #  android_id: ^0.4.0
  device_info_plus: ^11.3.0

  # Firebase Messaging
  firebase_messaging: ^15.2.4
  firebase_core: ^3.13.0
  flutter_local_notifications: 18.0.1
  url_strategy: ^0.3.0
  firebase_analytics: ^11.4.5
  cloud_firestore: ^5.6.7

  #Google Maps Location
  google_maps_flutter: ^2.10.1
  geolocator: 13.0.2
  geocoding: 3.0.0
  location: 7.0.1
  widget_to_marker: ^1.0.6

  # Utility
  collection: 1.19.1
  easy_debounce: 2.0.3
  url_launcher: 6.3.1
  flutter_widget_from_html: ^0.15.3
  fluttertoast: ^8.2.12
  html_unescape: ^2.0.0
  carousel_slider: ^5.0.0
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.4

  #message swipe
  swipe_to: 1.0.6

  # Social Sign in
  sign_in_with_apple: ^6.1.4
  google_sign_in: ^6.2.2
  better_player:
    git:
      url: https://github.com/MannFlutter/video_player_demo.git
      ref: main
  get_ip_address: ^0.0.7
  firebase_auth: ^5.5.2
  flutter_branch_sdk: ^8.4.1
  installed_apps: ^1.6.0
  change_app_package_name: ^1.5.0
  animated_text_kit: ^4.2.2
  flutter_multi_select_items: ^0.4.3
  double_tap_to_exit: ^1.0.3


dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
    # The "flutter_lints" package below contains a set of recommended lints to
    # encourage good coding practices. The lint set provided by the package is
    # activated in the `analysis_options.yaml` file located at the root of your
    # package. See that file for information about deactivating specific lint
    # rules and activating additional ones.

  flutter_gen: ^5.9.0
  pretty_dio_logger: ^1.4.0
  flutter_lints: ^5.0.0
  build_runner:
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  injectable_generator: ^2.6.2
  flutter_gen_runner:
  lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/app_Icon_3.png"
  image_path_android: "assets/images/app_Icon_3.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_Icon_3.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/app_Icon_3.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/app_Icon_3.png"

dependency_overrides:
  archive: ^3.0.0
  geolocator_android: 4.6.1
  collection: 1.19.0
  video_player_android: ^2.4.14

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/background/
    - assets/fonts/
    - assets/lottie/
    - assets/json/
    - assets/lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #  fonts:
  #    - family: Inter
  #      fonts:
  #        - asset: assets/fonts/inter/Inter-Black.ttf
  #        - asset: assets/fonts/inter/Inter-BlackItalic.ttf
  #        - asset: assets/fonts/inter/Inter-Bold.ttf
  #        - asset: assets/fonts/inter/Inter-BoldItalic.ttf
  #        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
  #        - asset: assets/fonts/inter/Inter-ExtraBoldItalic.ttf
  #        - asset: assets/fonts/inter/Inter-ExtraLight-BETA.ttf
  #        - asset: assets/fonts/inter/Inter-ExtraLightItalic-BETA.ttf
  #        - asset: assets/fonts/inter/Inter-Italic.ttf
  #        - asset: assets/fonts/inter/Inter-Light-BETA.ttf
  #        - asset: assets/fonts/inter/Inter-LightItalic-BETA.ttf
  #        - asset: assets/fonts/inter/Inter-Medium.ttf
  #        - asset: assets/fonts/inter/Inter-MediumItalic.ttf
  #        - asset: assets/fonts/inter/Inter-Regular.ttf
  #        - asset: assets/fonts/inter/Inter-SemiBold.ttf
  #        - asset: assets/fonts/inter/Inter-SemiBoldItalic.ttf
  #        - asset: assets/fonts/inter/Inter-Thin-BETA.ttf
  #        - asset: assets/fonts/inter/Inter-ThinItalic-BETA.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
